version: 0.2

phases:
  install:
    commands:
      - echo "Installing OpenJDK 17..."
      - apt-get update
      - apt-get install -y wget
      - wget -qO - https://apt.corretto.aws/corretto.key | apt-key add -
      - add-apt-repository 'deb https://apt.corretto.aws stable main'
      - apt-get update
      - apt-get install -y java-17-amazon-corretto-jdk
  pre_build:
    commands:
      - echo Pre-build phase
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
