version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      echo Installing dependencies...
      mvn install -DskipTests=true  # Skips tests during dependency installation

  build:
    commands:
      echo Building the Java project...
      mvn clean install  # Build the project using Maven

  post_build:
    commands:
      echo Build completed.
      # Optionally, you can upload build artifacts or run tests