AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Elastic Beanstalk Application Deployment with CodePipeline

Parameters:
  ApplicationName:
    Type: String
    Description: The name of the application
    Default: TranscriptionApp

  ApplicationVersion:
    Type: String
    Description: Application version
    Default: v1.0

  GitHubOwner:
    Type: String
    Description: GitHub username or organization name

  GitHubRepo:
    Type: String
    Description: The name of the GitHub repository

  GitHubBranch:
    Type: String
    Default: main
    Description: The GitHub branch to deploy from

Resources:
  # Elastic Beanstalk Application
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName

  # Elastic Beanstalk Environment
  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: !Sub "${ApplicationName}-env"
      VersionLabel: !Ref ApplicationVersion
      OptionSettings:
        - Namespace: "aws:elasticbeans
